# General
env: dev
validate_ssl_cert: true

# AWS
aws:
  default_region: us-west-2

# Test Report and Emailing
report:
  s3_upload:
    enabled: true
    bucket: hmklabs-dotcom-dev-qa-automation-artifacts
